pipeline {
    agent any

    environment {
        // Nom de votre credential Nexus configuré dans Jenkins
        NEXUS_CREDENTIALS = 'deploymentRepo'
    }

    stages {
        stage('Clean and Build') {
            steps {
                script {
                    // Nettoyage et compilation avec Maven
                    sh 'mvn clean install -DskipTests'
                }
            }
        }

        stage('Deploy to Nexus') {
            steps {
                script {
                    // Utilisation des credentials Nexus pour l'authentification
                    withCredentials([usernamePassword(credentialsId: NEXUS_CREDENTIALS, passwordVariable: 'NEXUS_PASSWORD', usernameVariable: 'NEXUS_USERNAME')]) {
                        // Commande Maven pour déployer l'artefact vers Nexus
                        sh """
                            mvn deploy \
                            -DskipTests \
                            -DaltDeploymentRepository=nexus::default::http://192.168.56.146:8081/repository/maven-releases/ \
                            -Dnexus.username=${NEXUS_USERNAME} \
                            -Dnexus.password=${NEXUS_PASSWORD}
                        """
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Déploiement vers Nexus réussi!'
        }
        failure {
            echo 'Le déploiement vers Nexus a échoué.'
        }
    }
}

