pipeline {
    agent any

    environment {
        // Nom de votre credential Nexus configuré dans Jenkins
        NEXUS_CREDENTIALS = 'deploymentRepo'
    }

    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm // Clonage du code depuis votre dépôt Git
            }
        }

        stage('Verify Directory Structure') {
            steps {
                script {
                    // Vérifier la structure du répertoire pour s'assurer que pom.xml est là
                    sh 'echo "Liste des fichiers dans le répertoire courant:"'
                    sh 'ls -la' // Liste les fichiers et répertoires dans le répertoire courant
                    // Vérifiez le répertoire kaddem2/src pour s'assurer que pom.xml est présent
                    sh 'ls -la kaddem2/src' // Liste les fichiers dans le répertoire src
                }
            }
        }

        stage('Clean and Build') {
            steps {
                script {
                    // Changer de répertoire pour le dossier où pom.xml est situé, ici kaddem2/src
                    dir('kaddem2/src') {  // Assurez-vous que le chemin vers 'src' est correct
                        // Nettoyage et compilation avec Maven
                        sh 'mvn clean install -DskipTests'
                    }
                }
            }
        }

        stage('Deploy to Nexus') {
            steps {
                script {
                    // Utilisation des credentials Nexus pour l'authentification
                    withCredentials([usernamePassword(credentialsId: NEXUS_CREDENTIALS, passwordVariable: 'NEXUS_PASSWORD', usernameVariable: 'NEXUS_USERNAME')]) {
                        // Commande Maven pour déployer l'artefact vers Nexus
                        sh """
                            mvn deploy \
                            -DskipTests \
                            -DaltDeploymentRepository=nexus::default::http://192.168.56.146:8081/repository/maven-releases/ \
                            -Dnexus.username=${NEXUS_USERNAME} \
                            -Dnexus.password=${NEXUS_PASSWORD}
                        """
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Déploiement vers Nexus réussi!'
        }
        failure {
            echo 'Le déploiement vers Nexus a échoué.'
        }
    }
}
